stages: 
    - build

build:
    image: docker:19.03.12
    stage: build
    # services:
    #     - docker:19.03.12-dind
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE/poupay-database:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    before-script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - docker build -f ./bd/Dockerfile -t $IMAGE_TAG ./bd
        - docker push $IMAGE_TAG
