name: 'Database image'

on:
  push:
    branches: 
      - main
    paths:
      - 'bd/**'
      - '.github/workflows/database.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  USER_REPO: poupay-finances

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build database image
        env:
          DOCKER_REPO: $REGISTRY/$USER_REPO
          IMAGE_TAG: $DOCKER_REPO/poupay-database:$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER
        run: docker build -f ./bd/Dockerfile -t $IMAGE_TAG ./bd

      - name: Login Github Packages
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push $IMAGE_TAG